name: server
description: server.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0-15.0.dev <3.0.0"

dependencies:
  http_server: ^1.0.0
  mongo_dart: ^0.7.2
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.2
  shelf_web_socket: ^1.0.1

dev_dependencies:
  shelf_router_generator: ^1.0.1
  build_runner: ^2.1.7
