declare module "slash2";
declare module "*.less";
declare module "*.module.scss";
declare module "*.scss";
declare module "*.svg";
declare module "*.png";
declare module "*.jpg";
declare module "*.jpeg";
declare module "*.gif";
declare module '*.ico'
declare module "*.bmp";
declare module "*.tiff";
